config/routes.rb
CensusData::Application.routes.draw do
  resources :children

  resources :people

  resources :relationship_statuses

  

end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :parent, class_name: "Person", foreign_key: "parent_id"
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :relationship_status 
  has_many :children
end

app/models/relationship_status.rb
class RelationshipStatus < ActiveRecord::Base
  has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    @children = Child.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to new_child_path, notice: 'Child was successfully created.' }
        format.json { render action: 'show', status: :created, location: @child }
      else
        format.html { render action: 'new' }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:surname, :forename, :age, :gender, :in_school, :in_work, :occupation, :parent_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to new_person_path, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:surname, :forename, :age, :house_number, :street, :occupation, :husbands_occupation, :industry, :place_of_birth, :position_in_household, :relationship_status_id)
    end
end

app/controllers/relationship_statuses_controller.rb
class RelationshipStatusesController < ApplicationController
  before_action :set_relationship_status, only: [:show, :edit, :update, :destroy]

  # GET /relationship_statuses
  # GET /relationship_statuses.json
  def index
    @relationship_statuses = RelationshipStatus.all
  end

  # GET /relationship_statuses/1
  # GET /relationship_statuses/1.json
  def show
  end

  # GET /relationship_statuses/new
  def new
    @relationship_status = RelationshipStatus.new
  end

  # GET /relationship_statuses/1/edit
  def edit
  end

  # POST /relationship_statuses
  # POST /relationship_statuses.json
  def create
    @relationship_status = RelationshipStatus.new(relationship_status_params)

    respond_to do |format|
      if @relationship_status.save
        format.html { redirect_to @relationship_status, notice: 'Relationship status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @relationship_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @relationship_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationship_statuses/1
  # PATCH/PUT /relationship_statuses/1.json
  def update
    respond_to do |format|
      if @relationship_status.update(relationship_status_params)
        format.html { redirect_to @relationship_status, notice: 'Relationship status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @relationship_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationship_statuses/1
  # DELETE /relationship_statuses/1.json
  def destroy
    @relationship_status.destroy
    respond_to do |format|
      format.html { redirect_to relationship_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship_status
      @relationship_status = RelationshipStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relationship_status_params
      params.require(:relationship_status).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relationship_statuses_helper.rb
module RelationshipStatusesHelper
end

app/views/census_records/_form.html.erb
<%= form_for(@census_record) do |f| %>
  <% if @census_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@census_record.errors.count, "error") %> prohibited this census_record from being saved:</h2>

      <ul>
      <% @census_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :forename %><br>
    <%= f.text_field :forename %>
  </div>
	
  <div class="field">
    <%= f.label :position_in_household %><br>
    <%= f.text_field :position_in_household %>
  </div>
  <div class="field">
    <%= f.label :relationship_status %><br>
    <%= collection_select(:census_record, :relationship_status_id, RelationshipStatus.all, :id, :description) %>
  </div>

  <div class="field">
    <%= f.label :house_number %><br>
    <%= f.text_field :house_number %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>

  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>

  <div class="field">
    <%= f.label :place_of_birth %><br>
    <%= f.text_field :place_of_birth %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname, value: Person.last.surname %>
  </div>
  <div class="field">
    <%= f.label :forename %><br>
    <%= f.text_field :forename %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :parent %><br>
    <%= f.select(:parent_id, Person.all.map { |p| [ "#{p.surname}, #{p.forename}", p.id ] }.reverse) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<h1>Listing children</h1>

<%= link_to 'New Child', new_child_path %>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Forename</th>
      <th>Age</th>
      <th>Gender</th>
      <th>In school</th>
      <th>In work</th>
      <th>Occupation</th>
      <th>Parent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.surname %></td>
        <td><%= child.forename %></td>
        <td><%= child.age %></td>
        <td><%= child.gender %></td>
        <td><%= child.in_school %></td>
        <td><%= child.in_work %></td>
        <td><%= child.occupation %></td>
        <td><%= "#{child.parent.surname}, #{child.parent.forename}" %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @child.surname %>
</p>

<p>
  <strong>Forename:</strong>
  <%= @child.forename %>
</p>

<p>
  <strong>Age:</strong>
  <%= @child.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @child.gender %>
</p>

<p>
  <strong>In school:</strong>
  <%= @child.in_school %>
</p>

<p>
  <strong>In work:</strong>
  <%= @child.in_work %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @child.parent_id %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CensusData</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :forename %><br>
    <%= f.text_field :forename %>
  </div>
  <div id="position_in_household" class="field">
    <%= f.label :position_in_household %><br>
    <%= f.text_field :position_in_household %>
  </div>
  <div id="relationship_status" class="field">
    <%= f.label :relationship_status %><br>
    <%= collection_select(:person, :relationship_status_id, RelationshipStatus.all, :id, :description) %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :husbands_occupation %><br>
    <%= f.text_field :husbands_occupation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<%= link_to 'New Person', new_person_path %>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Forename</th>
      <th>Age</th>
      <th>Occupation</th>
      <th>Husband's Occupation</th>
      <th>Position in household</th>
      <th>Relationship status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.surname %></td>
        <td><%= person.forename %></td>
        <td><%= person.age %></td>
        <td><%= person.occupation %></td>
        <td><%= person.husbands_occupation %></td>
        <td><%= person.position_in_household %></td>
        <td><%= person.relationship_status.description %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @person.surname %>
</p>

<p>
  <strong>Forename:</strong>
  <%= @person.forename %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>House number:</strong>
  <%= @person.house_number %>
</p>

<p>
  <strong>Street:</strong>
  <%= @person.street %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @person.occupation %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @person.industry %>
</p>

<p>
  <strong>Place of birth:</strong>
  <%= @person.place_of_birth %>
</p>

<p>
  <strong>Position in household:</strong>
  <%= @person.position_in_household %>
</p>

<p>
  <strong>Relationship status:</strong>
  <%= @person.relationship_status_id %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/relationship_statuses/_form.html.erb
<%= form_for(@relationship_status) do |f| %>
  <% if @relationship_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship_status.errors.count, "error") %> prohibited this relationship_status from being saved:</h2>

      <ul>
      <% @relationship_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationship_statuses/edit.html.erb
<h1>Editing relationship_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship_status %> |
<%= link_to 'Back', relationship_statuses_path %>

app/views/relationship_statuses/index.html.erb
<h1>Listing relationship_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @relationship_statuses.each do |relationship_status| %>
      <tr>
        <td><%= relationship_status.description %></td>
        <td><%= link_to 'Show', relationship_status %></td>
        <td><%= link_to 'Edit', edit_relationship_status_path(relationship_status) %></td>
        <td><%= link_to 'Destroy', relationship_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship status', new_relationship_status_path %>

app/views/relationship_statuses/new.html.erb
<h1>New relationship_status</h1>

<%= render 'form' %>

<%= link_to 'Back', relationship_statuses_path %>

app/views/relationship_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @relationship_status.description %>
</p>

<%= link_to 'Edit', edit_relationship_status_path(@relationship_status) %> |
<%= link_to 'Back', relationship_statuses_path %>